### ISSUE TITLE
Install GCtree

### ISSUE THREAD

**Issue by NikaAb** [NikaAb/BCR_intraclonal_diversity#3]
First we have to install the Anaconda : 

1- Download the installer for python 3.7 from https://www.anaconda.com/products/individual#linux
It's a .sh file.

2 - Enter the following to install Anaconda for Python 3.7 by replacing the Anaconda3_xxxxxxxxxxxxx.sh with the name of your installer file : 
`bash Anaconda3_xxxxxxxxxxxxx.sh`

At this point you have probably installed the anaconda, let me know if it dost not work

Then let's start installing GCtree with these commands : 

Create a python 3.7 conda environment (named gctree )in bash
`conda create --name gctree python=3.7`

Activate the environment in bash
`source activate gctree`

Install too many packages :/ 
`conda install -c etetoolkit ete3 ete3_external_apps`
`conda install biopython matplotlib pandas scipy scons seaborn`
`conda install -c conda-forge nestly`
`conda install -c bioconda phylip`
`conda install -c cswarth seqmagick`
`conda install -c conda-forge jellyfish`

If you have no error, make sure that 
- you use python 3
- you have downloaded the GCtree repository

and try this from within the gctree repository directory  : 
`scons --inference --input=example/150228_Clone_3-8.fasta --outdir=test --converter=tas --naiveID=GL --jobs=2`

**Comment by LucileJeusset** [comment]
I tried to launch GCtree but at some point I got this error message : 
`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
python bin/gctree.py infer test/dnapars/outfile test/150228_Clone_3-8.counts --naive gl --outbase test/gctree > test/gctree.inference.log
Traceback (most recent call last):
  File "bin/gctree.py", line 1032, in <module>
    main()
  File "bin/gctree.py", line 1029, in main
    args.func(args)
  File "bin/gctree.py", line 640, in infer
    outfiles = [phylip_parse.parse_outfile(args.phylipfile, args.countfile, args.naive)]
  File "/home/administrator/Documents/Master2/S2/Stage/GCtree/bin/phylip_parse.py", line 107, in parse_outfile
    trees.append(build_tree(sequences, parents, counts, naive))
  File "/home/administrator/Documents/Master2/S2/Stage/GCtree/bin/phylip_parse.py", line 164, in build_tree
    tree = disambiguate(tree)
  File "/home/administrator/Documents/Master2/S2/Stage/GCtree/bin/phylip_parse.py", line 123, in disambiguate
    new_base = random.choice(ambiguous_dna_values[base])
KeyError: '-'
scons: *** [test/gctree.inference.parsimony_forest.p] Error 1
scons: building terminated because of errors.
`
During packages installation I had difficulties with ete3 and ete3_external_apps but I don't think it is related to that. Did you have this error message?

**Comment by NikaAb** [comment]
What do your sequences look like? do they have '-' somewhere as a base? it seems that scons doesn't recognize this symbol as a DNA base.

**Comment by LucileJeusset** [comment]
Indeed I used the file provide as an example and there are '-' in the first sequence. After modifying it, it works thank you!
